server:
  port: 8080

db:
  dsn: "host=39.105.2.5 user=goya password=goya123 dbname=goya_vision port=14210 sslmode=disable"

ffmpeg:
  bin: "ffmpeg"
  max_record: 16
  max_frame: 16

preview:
  provider: "mediamtx"
  mediamtx_bin: "mediamtx"
  max_preview: 10
  hls_base: "/live"

record:
  base_path: "./data/recordings"
  segment_sec: 300

ai:
  timeout: 10s
  retry: 2

jwt:
  secret: "goyavision-secret-change-in-production"
  expire: 2h
  refresh_exp: 168h
  issuer: "goyavision"

mediamtx:
  api_address: "http://39.105.2.5:9997"
  rtsp_address: "rtsp://39.105.2.5:8554"
  rtmp_address: "rtmp://39.105.2.5:1935"
  hls_address: "http://39.105.2.5:8888"
  webrtc_address: "http://39.105.2.5:8889"
  playback_address: "http://39.105.2.5:9996"
  record_path: "/nas/mediamtx/recordings/%path/%Y-%m-%d_%H-%M-%S"
  record_format: "fmp4"
  segment_duration: "1h"

minio:
  endpoint: "39.105.2.5:14250"
  access_key: "goyaminio"
  secret_key: "goyaminio"
  bucket_name: "goya-vision"
  use_ssl: false
